name: Shadow Radar Runner

on:
  push:
    branches: [ main ]
  #schedule:
   # - cron: '0 */4 * * *'  # Cada 4 horas
  workflow_dispatch:

jobs:
  run-radar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # Optimiza las ejecuciones repetitivas

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install discord.py httpx google-genai python-dotenv

      - name: Ejecutar Radar
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          ls -R
          python -u src/main.py

